import mongoose from "mongoose";

const captionSchema = new mongoose.Schema(
    {
        videoid: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "videofiles",
            required: true,
            index: true,
        },
        language: {
            type: String,
            default: "en",
        },
        label: {
            type: String,
            default: "English (Auto-generated)",
        },
        vttpath: {
            type: String,
            default: "",
        },
        cues: [
            {
                start: { type: Number, required: true }, // Start time in seconds
                end: { type: Number, required: true },   // End time in seconds
                text: { type: String, required: true },  // Caption text
            },
        ],
        autogenerated: {
            type: Boolean,
            default: true,
        },
        status: {
            type: String,
            enum: ["pending", "processing", "completed", "failed"],
            default: "pending",
        },
        errormessage: {
            type: String,
            default: "",
        },
        uploader: {
            type: String,
            default: "",
        },
    },
    {
        timestamps: true,
    }
);

export default mongoose.model("captions", captionSchema);
